FROM python:3.10-slim
WORKDIR /app

COPY docker-requirements_server.txt .
RUN python3 -m pip install -r docker-requirements_server.txt
COPY model/ model
COPY tensorflow_server.py .

ENTRYPOINT ["python3", "/app/tensorflow_server.py", "-d", "model"]
